### ISSUE TITLE
Second call to :infinite can't be interrupted

### ISSUE THREAD

**Issue by 17Genr** [urbit/archaeology#16] opened 2013-09-25 04:31 UTC
When running through the tutorial I tried to call :infinite a second time and my console was hung.  Testing futher, I fired up a new instance of urbit and it happened again as shown in this log:

me@live:~/urbit-git$ bin/vere xpier
vere: urbit home is /home/me/urbit
loom: loaded 6MB
time: ~2013.9.25..04.26.17..9795
ames: on localhost, UDP 42391.
http: live on 8080
rest: checkpoint to event 1088
rest: old 0ve.98aj9, new 0v1j.0dkgb
rest: replaying through event 1101
---------------- playback starting----------------
..............
---------------- playback complete----------------
! intr
~dattud-hinmed-rabsup-hocmer--folwen-ponrux-folhut-tipdyl/try=> :ls %
bin lib web
~dattud-hinmed-rabsup-hocmer--folwen-ponrux-folhut-tipdyl/try=> :infinite

The only way out is to kill the terminal.  

This is at commit  6a56562d4c3de2c0d39d3386ad5047db7f4d6161 pulled from https://github.com/urbit/urbit.git on Sept 24th running on 'Debian GNU/Linux 7.0' with a uname -a of 'Linux live 3.2.0-4-amd64 #1 SMP Debian 3.2.41-2+deb7u2 x86_64 GNU/Linux'.

**Comment by 17Genr** [comment] 2013-09-26 02:03
Trying again today, this time in an emacs term buffer, I got the same problem and tring to restart using 'vere xpier' looks like it ends up replaying to the hung point and never gives back a prompt.

**Comment by Walther** [comment] 2013-09-30 22:35
Confirmed on 8047d0d5121bdc3dec4e281c61e78fbbcf177cc5. It doesn't even have to be consecutive; you can run `:infinite`, hit ^C, run `(add 2 2)`, and `:infinite` again will cause an uninterruptible infinite loop.
Closing the terminal and re-running `bin/vere mypier` seemingly restores the system.

**Comment by ericfode** [comment] 2013-11-05 09:29
@17Genr @Walther can either of you confirm that this is still a bug?

**Comment by Walther** [comment] 2013-11-05 13:34
Still present on ad50b5dc83ebbdd16f9880161a64b9d28563535e. Tested like in the previous comment, run `:infinite`, hit ^C, run `(add 2 2)`, and `:infinite` again.

**Comment by cgyarvin** [comment] 2013-11-05 17:17
Yes it's still a bug.  Unix layer.  Something about the signal handling
seems to not recover from the first ^C.

The workaround is simply to kill -15 and restart.

**Comment by ghost** [comment] 2014-03-27 22:51
dupe of #53, now appears fixed.

**Closed as completed by ghost** 2014-03-27 22:51 UTC
Labels: bug, P2
