### ISSUE TITLE
^C not working until reboot of server

### ISSUE THREAD

**Issue by pgray** [urbit/archaeology#53] opened 2013-10-07 02:29 UTC
I am not sure how to describe the issue much more than the title.

Basically hitting ^C after executing :begin doesn't work until I've hit ^D and then run vere on my pier again.

After running vere, ^X will switch me back to the :begin process and then only can I kill it.

**Comment by SethTisue** [comment] 2013-11-15 21:17
I believe I experienced this as well. When working through the tutorial for the first time, ^C didn't work. Now, in subsequent `vere` runs (without rebuilding urbit or anything like that), it works fine.

**Comment by cgyarvin** [comment] 2013-11-15 21:39
Something is getting messed up with the signal handling, I think.
 Unfortunately a low priority...

**Comment by ghost** [comment] 2014-03-27 22:33
Dupe of #102, fixed hopefully by the same.

**Closed as completed by ghost** 2014-03-27 22:33 UTC
